# Generated by Django 2.2.2 on 2019-07-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190712_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='social_platform',
            new_name='platform',
        ),
    ]
