# Generated by Django 2.2.2 on 2019-07-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190713_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialUser',
            new_name='SocialPlatform',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='social_id',
            new_name='social',
        ),
    ]
