# Generated by Django 2.2.2 on 2019-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.AlterModelTable(
            name='eventpost',
            table='event',
        ),
    ]
