# Generated by Django 2.2.2 on 2019-07-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPost',
        ),
    ]
