# Generated by Django 2.2.2 on 2019-07-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190703_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='EventPost',
        ),
    ]
