# Generated by Django 2.2.2 on 2019-07-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0003_auto_20190703_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('stat_time', models.CharField(blank=True, max_length=20)),
                ('end_time', models.CharField(blank=True, max_length=20)),
                ('max_rsvp', models.IntegerField(blank=True)),
                ('current_rsvp', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=100)),
                ('main_text', models.TextField(blank=True, max_length=2000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
