# Generated by Django 2.2.2 on 2019-07-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190704_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='building_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Building'),
        ),
    ]
