# Generated by Django 2.2.2 on 2019-07-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190704_1401'),
        ('event', '0008_auto_20190704_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='url',
            new_name='event_page_url',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='writer',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='event_host',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='end_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='stat_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
