# Generated by Django 2.2.2 on 2019-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190704_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
