# Generated by Django 2.2.2 on 2019-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20190705_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='stat_time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
