# Generated by Django 2.2.2 on 2019-07-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20190707_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
