# Generated by Django 2.2.2 on 2019-07-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190707_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.CharField(blank=True, default='20190815', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='end_time',
            field=models.CharField(blank=True, default='11:00AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event_page_url',
            field=models.URLField(default='members.wework.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='main_text',
            field=models.TextField(blank=True, default='준비 중 입니다.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='max_rsvp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='photo_url',
            field=models.CharField(blank=True, default='https://res-5.cloudinary.com/wework/image/upload/c_fill,h_460,w_460/v1562114768/production/event/photo/05d4fdfb-041c-4b98-8b44-4face904388b.jpg', max_length=300),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='place',
            field=models.CharField(default='8층 메인라운지', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='start_time',
            field=models.CharField(blank=True, default='10:00AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='title',
            field=models.CharField(default='위워크 하반기 이벤트', max_length=50),
        ),
    ]
