# Generated by Django 2.2.2 on 2019-07-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190708_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Building'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='end_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='photo_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='start_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
