# Generated by Django 2.2.2 on 2019-07-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1811'),
        ('event', '0015_auto_20190708_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event_page_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='main_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventPost')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
