# Generated by Django 2.2.2 on 2019-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20190711_1518'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventrsvp',
            table='event_rsvp',
        ),
    ]
