# Generated by Django 2.2.2 on 2019-07-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1811'),
        ('event', '0018_eventreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreply',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventreply',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, to='user.User'),
        ),
    ]
