# Generated by Django 2.2.2 on 2019-07-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1811'),
        ('event', '0019_auto_20190712_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreply',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventreply',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
