# Generated by Django 2.2.2 on 2019-07-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1811'),
        ('event', '0021_auto_20190712_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCommemts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_commemts',
            },
        ),
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='rsvp_members',
            field=models.ManyToManyField(related_name='rsvp_members', through='event.EventRsvp', to='user.User'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event_host',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='user.User'),
        ),
        migrations.DeleteModel(
            name='EventReply',
        ),
        migrations.AddField(
            model_name='eventcommemts',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventPost'),
        ),
        migrations.AddField(
            model_name='eventcommemts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', to_field='user_id'),
        ),
    ]
