# Generated by Django 2.2.2 on 2019-07-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20190712_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcommemt',
            old_name='comments_text',
            new_name='comment_text',
        ),
    ]
