# Generated by Django 2.2.2 on 2019-07-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1811'),
        ('event', '0024_auto_20190712_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCommemt',
            new_name='EventComment',
        ),
        migrations.AlterModelTable(
            name='eventcomment',
            table='event_comment',
        ),
    ]
