# Generated by Django 2.2.2 on 2019-07-13 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_eventlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
