# Generated by Django 2.2.2 on 2019-07-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20190713_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
