# Generated by Django 2.2.2 on 2019-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20190713_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
