# Generated by Django 2.2.2 on 2019-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20190713_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='end_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='start_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
